### ISSUE TITLE
[Rules] 협업 규칙

### ISSUE THREAD

**Issue by 4923** [hufslion10th/welcome_kit#1]
### How to use
1. 본 repository를 fork
2. 본인이 작업하는 브랜치를 clone
  ```zsh
  # 형식: git clone -b <branch> <github repo>
  $ git clone -b FE https://github.com/본인의github계정/welcome_kit.git
  ```
3. hufslion10th/welcome_kit repo를 upstream 등록: 동기화를 위함
  ```zsh
  # 형식 git remote add upstream <github repo>
  $ git remote add upstream https://github.com/hufslion10th/welcome_kit.git
  ```
4. 작업 전 원본 repo와 동기화
  ```zsh
  # 본인의 작업 branch에서 진행
  # (-ff-only) 내 커밋만 유지하기 위함
  git pull --ff-only origin main
  ```
5. 작업 후 본인의 branch에 commit
  ```zsh
  git push origin <branch>
  ```
6. (github) **fork한 repo**의 **본인 branch**에서 (e.g. 4923/welcome_kit 의 FE branch) pull request 생성. 이 때 target은 hufslion10th/welcome-kit 의 **main** 브랜치.
7. (github) assignees에는 본인, reviewer에는 같은 작업을 하고 있는 사람 또는 @4923

**Comment by 4923** [comment]
궁금하거나 제안할 사안 있을 시 본 issue에 comment 달아주세요~ @JungWooJin97 
- FE 브랜치 세팅해두었으니 사용하시면 됩니다.

**Comment by JungWooJin97** [comment]
혹시 커밋 규칙이 따로 있을까요?

**Comment by Parkjju** [comment]
원본 레포지토리에 날린 다른 분의 PR을 로컬에서 직접 돌려보고 싶으시면 아래 코드를 입력해주세요! :)

```sh
git fetch upstream pull/ID/head:BRANCHNAME
```
PR페이지 링크 보시면 각 url에 pull id가 부여되어 있습니다. BRANCHNAME은 자유롭게 작성해주셔서 위 코드를 실행하시면 로컬에 브랜치가 하나 생성됩니다.

```sh
git checkout BRANCHNAME
```
체크아웃 하셔서 코드 돌려보시고, 아직 PR단계이니 이후 삭제하면 될 것 같습니다 :) 

@4923 @JungWooJin97 @DohuiKo 

## Reference
[Github docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)
