### ISSUE TITLE
[Contents] 아기사자로 살아남기

### ISSUE THREAD

**Issue by 4923** [hufslion10th/welcome_kit#3]
# 멋사 적응 guide (a.k.a. 아기사자로 살아남기)

### 목적
> 신규 동아리원의 적응을 돕고 활동하기 위한 가이드를 제공한다.

### 내용 상세
concept: 초원, 동물의 왕국, 뭐 그런거 ... (e.g. `아기사자에겐 낯선 초원... 어떻게 살아 남아야 할까?`)

세 가지 종류로 나누어 제작
1. 초원의 규칙 == 멋사 기본 규칙
2. 생존편 == 기본 적응
3. 발전편 == 개발자로서의 자세

### 기타
규칙이나 내용은 계속 제안 받습니다.

**Comment by 4923** [comment]
> 아기사자에겐 낯선 개발자의 초원... 어떻게 살아 남아야 할까?

### 초원의 규칙 (한 페이지 소모)
- 비대면 세션이지만 친해질 수 있어요. 카메라는 ON, 마이크는 필요시에만 ON
- 모르는게 있다면 언제든 Slack또는 손들기 버튼! ✋ 
- Slack 공지를 확인했다면 언제나 ✅ 이모지를 다세요!
- 기본 규칙이 더 있을텐데... 뭐가 있나... 🤔 

### 생존편 (한 페이지 소모)
1. 동료를 찾아라!
    - Slack의 이모지를 활용하면 내적 친밀감이 쌓여요.
    - 관심사가 비슷한 아기사자를 눈여겨보세요. 프로젝트 파트너가 될 수도 있답니다.
2. 동료를 도와라!
    - 질문은 운영진만 답할 수 있는게 아니예요! 곤경에 처한 동료와 함께 코딩해요!
    - 내가 어렵다면 다른사람도 어렵다는걸 기억하세요 😉 
3. 도움을 요청해라!
      - 궁금한게 생겼다? 주저말고 `@운영진` 을 태그하세요. 모두 같은 과정을 거쳐온 사람들이랍니다.

### 발전편 (한 페이지 소모)
1. 구글을 믿어라!
      - 구글링 하는 방법을 찾아내세요. 에러코드를 전부 읽고, 무엇을 검색해야 하는지 찾아내는 습관을 길러야 합니다.
2. 모두 기록하자!
      - 개발자의 기록, 공유문화에 익숙해지세요. 🖊️ 
      - 일일커밋과 TIL이 귀찮아도 언젠가 큰 도움이 될 거랍니다.
3. 개발하는 습관을 들이자!
      - 언제나 열려있는 gather town에서 함께 코딩하면 지치지 않아요! 🏡 
      - 모각코, 장소 대관 등이 필요하다면 언제든 운영진에게 건의해주세요!

**Comment by 4923** [comment]
## OX 퀴즈

| 문제 | 답 |
| :- | :- |
| 외대 멋사 10기는 행정부, 사법부, 입법부로 구성된다. | X |
| 멋사 10기는 개발트랙, 기획트랙 두개로 구분된다. | X |
| 다음 중 Slack 공지를 확인했을 때 달아야 하는 이모지는? | ✔️  ☑️   ✅ |
| 세션은 비대면으로 진행되고, 마이크는 필요시에만 켜야 한다. | O |
| 질의응답 채널에는 운영진만 답을 달 수 있다. | X | 
| 이번 달의 질문왕은 질문을 가장 많이 한 아기사자에게 부여되는 칭호다. | O |
| 멋사 10기의 해커톤은 7월에 이루어진다. | X |
| 2학기 MOD는 NC Soft와 협업한다. | X |

필요시 각자 추가

**Comment by 4923** [comment]
참고할만한 온보딩 가이드북/키트

- 입사 두시간 만에 실무에 적응하도록 돕자!
  - https://brunch.co.kr/@class101/22
- 온보딩 경험 설계를 위한 콘텐츠 플로우
  - https://blog.krafton.com/4557/amp/

**Comment by 4923** [comment]
남은 Task

- [ ] Track별 인원구성
- [ ] 더 나은 질문을 해보자

**Comment by hotsun1508** [comment]
### 일정로드맵부분 디자인 완료입니다. @우진님
![image](https://user-images.githubusercontent.com/60880176/159065082-cf2f73c1-359f-4300-a796-e56eae34c796.png)

##애니메이션 
prototype으로 표시해두었는데 헷갈리실만한 부분만 남겨둡니다.
- `>` 이 화살표들은 그대로 따라가주시면 되고, 구현은 @Parkjju 님께 여쭤보시면 될 것 같아요!  밑에 첨부한 부분이랑 똑같습니다.
![image](https://user-images.githubusercontent.com/60880176/159064600-b5f0ae89-8c16-4d7d-937b-58a862d08d6d.png)

- 맨 오른쪽 "일정" 부분에 달력 아이콘을 클릭하면 일정표가 나오구요, 한번 더 클릭하면 접힙니다.
- 사자는 hovering하면 말풍선이 나옵니다.
![image](https://user-images.githubusercontent.com/60880176/159065214-d7d00309-bc11-40e3-a5d4-c43665869953.png)

힘 닿는데까지 해주시고 시간 부족하시면 내일 제가 애니메이션 없는 버전으로 만들어 놓을게요 :)) 감사합니다 🚀

**Comment by 4923** [comment]
가이드 UI 및 콘텐츠 제작 완료.
close.
