### ISSUE TITLE
[Contents] 일정, 로드맵

### ISSUE THREAD

**Issue by hotsun1508** [hufslion10th/welcome_kit#34]
# 기능명
### 목적
> 멋사 10기 일정 가이드를 제공한다.

### 내용 상세
- 프론트엔드, 백엔드, 기획/디자인 파트로 구분

### 기타
- 애니메이션 효과 있음...

**Comment by hotsun1508** [comment]
### 일정로드맵부분 디자인 완료입니다. @JungWooJin97 
![image](https://user-images.githubusercontent.com/60880176/159065082-cf2f73c1-359f-4300-a796-e56eae34c796.png)

## 애니메이션 
prototype으로 표시해두었는데 헷갈리실만한 부분만 남겨둡니다.
- `>` 이 화살표들은 그대로 따라가주시면 되고, 구현은 @Parkjju 님께 여쭤보시면 될 것 같아요!  밑에 첨부한 부분이랑 똑같습니다.
![image](https://user-images.githubusercontent.com/60880176/159064600-b5f0ae89-8c16-4d7d-937b-58a862d08d6d.png)

- 맨 오른쪽 "일정" 부분에 달력 아이콘을 클릭하면 일정표가 나오구요, 한번 더 클릭하면 접힙니다.
- 사자는 hovering하면 말풍선이 나옵니다.
![image](https://user-images.githubusercontent.com/60880176/159065214-d7d00309-bc11-40e3-a5d4-c43665869953.png)

힘 닿는데까지 해주시고 시간 부족하시면 내일 제가 애니메이션 없는 버전으로 만들어 놓을게요 :)) 감사합니다 🚀

**Comment by 4923** [comment]
개발 완료되었으니 close 합니다 수고하셨습니다
