### ISSUE TITLE
[Contents] UI 레이아웃 1차안 (검토 必)

### ISSUE THREAD

**Issue by 4923** [hufslion10th/welcome_kit#5]
# 레이아웃 및 페이지명 확정

### 목적
개발단계로 넘어가기 위한 레이아웃 초안 확정

### 내용 상세
- [figma prototype](https://www.figma.com/proto/MVxwXPWDwvbjmx9x2k36z1/%EB%A9%8B%EC%82%AC10%EA%B8%B0-%EC%98%A8%EB%9D%BC%EC%9D%B8-%EC%9B%B0%EC%BB%B4%ED%82%A4%ED%8A%B8?page-id=0%3A1&node-id=2%3A6&scaling=min-zoom&starting-point-node-id=13%3A12)

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/60145951/157549887-8f48d89f-4f3c-4143-ac5a-f80ff8a5dbc1.png">

- [miro wireframe](https://miro.com/app/board/uXjVOG4tkSA=/?invite_link_id=905166868682)
    - [miro board invite: as a editor](https://miro.com/welcomeonboard/TXFGMEo1YkxGUWZlRDJZSnBpeE9pTlRVcjdqWDJwOGIwQ3ZsbHFwNDJuNUFQcndUVE1tcDVtTncxaDRRd1I5M3wzNDU4NzY0NTE3MTYzNzE3MTE1?invite_link_id=11474553352)
<img width="1562" alt="image" src="https://user-images.githubusercontent.com/60145951/157549841-8a3fe6d2-86d6-407a-af43-02c5391228af.png">

### 기타
- 해당 내용 구현 가능한지 여부 확인 필요
  - 텍스트 처리: 텍스트 그대로 추가 할 것인가 이미지로 만들어서 붙여넣을 것인가? 🤔
  - 그 외 결정/구체화 필요한 사안이 있다면 확인 
- 디자인 보완 필요
- 내용 보완: 최종 합격자에 따라 달라지는 내용들

**Comment by 4923** [comment]
이 부분 한번 보고 피드백 주시면 감사하겠습니다.

### 디자인
@DohuiKo 님이 주신 아이디어에서 보완해봤지만 디자인... 은 저게 제 한계입니다 😞 
홈화면으로 돌아가는 버튼이 너무 애매한데 걸쳐있는데 뭐 어디에 붙일지 모르겠네요 💭 
아이디어 있으면 figma에 댓글 or 반영 부탁드립니다.

### 논의사항
1. 개발 들어가기 전에 확정해야 할 사안들: 레이아웃 외
2. 기술스택: 사용해보고 싶으신 것으로, 경준님 우진님 두분이서 논의해주세요.
3. 개발공수 파악: 보시고 이상 없으면 뼈대부터 바로 짜버리죠~ 시간 남으면 효과 추가하는 방향으로 갑시다.
@Parkjju @JungWooJin97

**Comment by 4923** [comment]
아니... 아니면 데스크탑 폴더형식으로 배치하는것도 괜찮을듯?
js로 커서 변경 가능한가 실제 컴퓨터에서 클릭하는것처럼 [커서](https://user-images.githubusercontent.com/60145951/157585798-7d077dc9-7589-49e4-b0f1-6908534c863c.png)효과 넣고,
각 항목들은 폴더 (도트컨셉) 로 마련해서 열게 만드는것도 괜찮겠다.

우진님이 마련해주신 페이지가 실물같다기보단 '웹 페이지' 같아서 이쪽 디자인도 고려

**Comment by hotsun1508** [comment]
> 이 부분 한번 보고 피드백 주시면 감사하겠습니다.
> 
> ### 디자인
> @DohuiKo 님이 주신 아이디어에서 보완해봤지만 디자인... 은 저게 제 한계입니다 😞 홈화면으로 돌아가는 버튼이 너무 애매한데 걸쳐있는데 뭐 어디에 붙일지 모르겠네요 💭 아이디어 있으면 figma에 댓글 or 반영 부탁드립니다.
> 
> ### 논의사항
> 1. 개발 들어가기 전에 확정해야 할 사안들: 레이아웃 외
>    
>    * welcome-kit 페이지 좌상단의 0번 컴포넌트 (운영진 캐릭터 아이콘들) 는 rolling-paper 페이지로 이동되므로 개별 분리하실 필요 없습니다
>    * 다만 rolling-paper 페이지에서는 운영진 캐릭터를 개별 아이콘화 하여 클릭시 다른 팝업이 나타나도록 만들어야 할 듯 합니다. 가능하신지 확인 필요해요.
>    * 이외 구현이 까다로운 레이아웃이 있다면 알려주세요
> 2. 기술스택: 사용해보고 싶으신 것으로, 경준님 우진님 두분이서 논의해주세요.
> 3. 개발공수 파악: 보시고 이상 없으면 뼈대부터 바로 짜버리죠~ 시간 남으면 효과 추가하는 방향으로 갑시다.
>    @Parkjju @JungWooJin97

홈화면 돌아가는 버튼 그냥 딱 하단 중간 위치에 넣어줘도 이쁜 것 같아욤 ~!
![image](https://user-images.githubusercontent.com/60880176/157692258-0e6c00eb-3bf3-40da-8d38-b1fead07ee7e.png)
디자인은 시간날 때마다 보면서 코멘트 달겠습니다. 😆

**Comment by 4923** [comment]
우선 도희님이 주신 피드백 comment로 정리하겠습니다. (내일...)
